BennyBooksWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BennyBooksWeb.DataAccess;
using BennyBooks.DataAccess.Repository.IRepository;
using BennyBooks.Models;
using Microsoft.AspNetCore.Mvc;
using log4net;
using Microsoft.EntityFrameworkCore;

namespace BennyBooksWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class CoverTypeController : Controller
{
    private readonly IUnitOfWork _unityOfWork; // ApplicationDbContext is now hosted in Irepository and reference in Program.cs

    public CoverTypeController(IUnitOfWork unityOfWork) // Constructor being passed db from Program.cs
    {
        _unityOfWork = unityOfWork;
    }

    public IActionResult Index() // to Add new view, right click this function and Add New View and Select "Razor View"
    {
        IEnumerable<CoverType> objCategoryList = _unityOfWork.CoverType.GetAll(); // Grabs all columns in the database, no sql required, look into LINQ            
        return View(objCategoryList);
    }

    // GET
    public IActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="obj"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CoverType obj) // Add to the database
    {
        if (string.IsNullOrWhiteSpace(obj.Name))
        {
            ModelState.AddModelError("name", "The Name cannot be made of only whitespace."); // key for AddModel can be CustomerError or field
        }
        // Checks to make sure the model is valid
        if (ModelState.IsValid && !string.IsNullOrWhiteSpace(obj.Name))
        {
            obj.Id = Guid.NewGuid();
            await _unityOfWork.CoverType.AddAsync(obj); // Add to the database
            await _unityOfWork.SaveAsync();
            TempData["success"] = "obj created successfully";

            return RedirectToAction(nameof(Index));
        }
        return View(obj);

    }

    // MIGHT BE A GOOD IDEA TO CREATE A CLASS TO HANDLE SIMLAR CHECKS LIKE UPDATING THE DATABASE
    // GET
    public IActionResult Edit(Guid? id)
    {
        if (id == null) return NotFound();
        //var categoryFromDb = _db.Categories.Find(id);
        //var categoryFromDbSingle = _db.Categories.SingleOrDefault(c => c.Id == id);
        var categoryFromDbFirst = _unityOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);

        if (categoryFromDbFirst == null) return NotFound();

        return View(categoryFromDbFirst);
    }

    // GET View Must be named exactly the same as this get
    public IActionResult Delete(Guid? id)
    {
        if (id == null || _unityOfWork == null) return NotFound();

        var categoryFromDbFirst = _unityOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);

        if (categoryFromDbFirst == null) return NotFound();

        return View(categoryFromDbFirst);
    }


    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(CoverType obj)
    {
        // Validation check making sure fields don't match
        if (string.IsNullOrWhiteSpace(obj.Name))
        {
            ModelState.AddModelError("name", "The Name cannot be made of only whitespace."); // key for AddModel can be CustomerError or field
        }


        // Checks to make sure the model is valid
        if (ModelState.IsValid && !string.IsNullOrWhiteSpace(obj.Name))
        {
            try
            {
                _unityOfWork.CoverType.Update(obj); // Update the database
                await _unityOfWork.SaveAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }

            return RedirectToAction(nameof(Index));
        }
        return View(obj);

    }

    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePOST(Guid? id)
    {
        var categoryFromDb = _unityOfWork.CoverType.GetFirstOrDefault(c => c.Id == id); // find obj to delete be id
        if (categoryFromDb == null) return NotFound();

        _unityOfWork.CoverType.Remove(categoryFromDb); // Update the database

        _unityOfWork.SaveAsync();
        TempData["success"] = "CoverType deleted successfully";

        return RedirectToAction(nameof(Index));
    }

}

BennyBooksWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType // Since we are not returning a type we can instead use the controller

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create CoverType</h2>
            <hr/>
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <!--Class is already available which allows us to use all properties from our model using the "asp-for"-->
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <!--checks validation, no need for js to check-->
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:10rem">Create</button>

        <!--Directs user to the home page-->
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width: 10rem">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        // Uses partial view, use _ to indicated a partialview. Makes it so validation happens on Client side not server side(Controller)
        <partial name="_ValidationScriptsPartial" />
    }
}

BennyBooksWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType // Since we are not returning a type we can instead use the controller

<form method="post" asp-action="DeletePOST">
    @*Since the input fields are disabled we still need the Id to be passed so it can be deleted*@
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Cover Page</h2>
            <hr/>
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <!--Class is already available which allows us to use all properties from our model using the "asp-for"-->
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div>
        @*
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div>*@
        <button type="submit" class="btn btn-danger" style="width:10rem">Delete</button>

        <!--Directs user to the home page-->
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width: 10rem">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        // Uses partial view, use _ to indicated a partialview. Makes it so validation happens on Client side not server side(Controller)
        <partial name="_ValidationScriptsPartial" />
    }
}

BennyBooksWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType // Since we are not returning a type we can instead use the controller

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit CoverType</h2>
            <hr/>
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <!--Class is already available which allows us to use all properties from our model using the "asp-for"-->
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <!--checks validation, no need for js to check-->
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:10rem">Update</button>

        <!--Directs user to the home page-->
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width: 10rem">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        // Uses partial view, use _ to indicated a partialview. Makes it so validation happens on Client side not server side(Controller)
        <partial name="_ValidationScriptsPartial" />
    }
}

BennyBooksWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType> // Whatever is being passed here must have a return that matches

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">CoverType List</h2>
        </div>
        <div class="col-6 text-end">
            <!--Associated button with category controller-->
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New CoverType
            </a>
        </div>
    </div>
    <br/><br/>


    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Cover Types
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Name
                    </td>
                    <td style="display:flex;">
                        @*Calls the action from the category controller*@
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id"
                            class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>

                            @*Calls the action from the category controller*@
                            <a asp-controller="CoverType" asp-action="Delete" asp-route-id="@obj.Id"
                            class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        
                        </div>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>