BennyBooksWeb/Areas/Admin/Controllers/CategoryController.cs
using BennyBooksWeb.DataAccess;
using BennyBooks.DataAccess.Repository.IRepository;
using BennyBooks.Models;
using Microsoft.AspNetCore.Mvc;
using log4net;
using Microsoft.EntityFrameworkCore;

namespace BennyBooksWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class CategoryController : Controller
{
    private readonly IUnitOfWork _unityOfWork; // ApplicationDbContext is now hosted in Irepository and reference in Program.cs

    public CategoryController(IUnitOfWork unityOfWork) // Constructor being passed db from Program.cs
    {
        _unityOfWork = unityOfWork;
    }

    public IActionResult Index() // to Add new view, right click this function and Add New View and Select "Razor View"
    {
        IEnumerable<Category> objCategoryList = _unityOfWork.Category.GetAll(); // Grabs all columns in the database, no sql required, look into LINQ            
        return View(objCategoryList);
    }

    // GET
    public IActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="category"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Category category) // Add to the database
    {
        if (category.Name == category.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name."); // key for AddModel can be CustomerError or field
        }
        // Checks to make sure the model is valid
        if (ModelState.IsValid && !string.IsNullOrWhiteSpace(category.Name))
        {
            category.Id = Guid.NewGuid();
            await _unityOfWork.Category.AddAsync(category); // Add to the database
            await _unityOfWork.SaveAsync();
            TempData["success"] = "Category created successfully";

            return RedirectToAction(nameof(Index));
        }
        return View(category);

    }

    // MIGHT BE A GOOD IDEA TO CREATE A CLASS TO HANDLE SIMLAR CHECKS LIKE UPDATING THE DATABASE
    // GET
    public IActionResult Edit(Guid? id)
    {
        if (id == null) return NotFound();
        //var categoryFromDb = _db.Categories.Find(id);
        //var categoryFromDbSingle = _db.Categories.SingleOrDefault(c => c.Id == id);
        var categoryFromDbFirst = _unityOfWork.Category.GetFirstOrDefault(c => c.Id == id);

        if (categoryFromDbFirst == null) return NotFound();

        return View(categoryFromDbFirst);
    }

    // GET View Must be named exactly the same as this get
    public IActionResult Delete(Guid? id)
    {
        if (id == null || _unityOfWork == null) return NotFound();

        var categoryFromDbFirst = _unityOfWork.Category.GetFirstOrDefault(c => c.Id == id);

        if (categoryFromDbFirst == null) return NotFound();

        return View(categoryFromDbFirst);
    }


    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Category category)
    {
        // Validation check making sure fields don't match
        if (category.Name == category.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name."); // key for AddModel can be CustomerError or field
        }


        // Checks to make sure the model is valid
        if (ModelState.IsValid && !string.IsNullOrWhiteSpace(category.Name))
        {
            try
            {
                _unityOfWork.Category.Update(category); // Update the database
                await _unityOfWork.SaveAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }

            return RedirectToAction(nameof(Index));
        }
        return View(category);

    }

    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePOST(Guid? id)
    {
        var categoryFromDb = _unityOfWork.Category.GetFirstOrDefault(c => c.Id == id); // find category to delete be id
        if (categoryFromDb == null) return NotFound();

        _unityOfWork.Category.Remove(categoryFromDb); // Update the database

        _unityOfWork.SaveAsync();
        TempData["success"] = "Category deleted successfully";

        return RedirectToAction(nameof(Index));
    }

}

BennyBooksWeb/Areas/Admin/Controllers/CompanyController.cs
using BennyBooksWeb.DataAccess;
using BennyBooks.DataAccess.Repository.IRepository;
using BennyBooks.Models;
using Microsoft.AspNetCore.Mvc;
using log4net;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using BennyBooks.Models.ViewModels;

namespace BennyBooksWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class CompanyController : Controller
{
    private readonly IUnitOfWork _unityOfWork; // ApplicationDbContext is now hosted in Irepository and reference in Program.cs

    public CompanyController(IUnitOfWork unityOfWork) // Constructor being passed db from Program.cs
    {
        _unityOfWork = unityOfWork;
    }

    public IActionResult Index() // to Add new view, right click this function and Add New View and Select "Razor View"
    {        
        return View();
    }

    
    
    // UPSERT replaces Create and Edit
    public IActionResult Upsert(Guid? id)
    // Used by company.js, Upsert.cshtml same for post
    {
        Company company = new Company(); // View now becomes tightly bounded by being managed in the ViewModel

        if (id == null || id == Guid.Empty)
        {
            return View(company);
        }
        else
        {
            // Will display edit page with all the data for a company
            company = _unityOfWork.Company.GetFirstOrDefault(u => u.Id == id); // Grab item and data
            return View(company);
        }

        
    }


    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Upsert(Company obj)
    {
        // Checks to make sure the model is valid
        if (ModelState.IsValid )//&& !string.IsNullOrWhiteSpace(obj.Title
        {
            try
            {
                if (obj.Id == Guid.Empty) // we are creating as there is no previous company
                {
                    await _unityOfWork.Company.AddAsync(obj); // Id is taken from the Upsert.cshtml
                    TempData["success"] = "Company created successfully";
                }
                else
                {
                    _unityOfWork.Company.Update(obj);
                    TempData["success"] = "Company updated successfully";
                }
                await _unityOfWork.SaveAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }

            return RedirectToAction(nameof(Index));
        }
        return View(obj);

    }



    #region API CALLS
    [HttpGet] // will get all of companies
    public IActionResult GetAll() //admin/company/getall
    {
        var companyLlist = _unityOfWork.Company.GetAll();
        return Json(new { data = companyLlist });
    }

    // POST
    [HttpDelete]
    public IActionResult Delete(Guid? id) // no need for a delete GET
    {
        var obj = _unityOfWork.Company.GetFirstOrDefault(c => c.Id == id); // find obj to delete be id
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }

        _unityOfWork.Company.Remove(obj); // Update the database

        _unityOfWork.SaveAsync();
        return Json(new { success = true, message = "Delete Successful" });
    }
    #endregion

}

BennyBooksWeb/Areas/Admin/Controllers/ProductController.cs
using BennyBooksWeb.DataAccess;
using BennyBooks.DataAccess.Repository.IRepository;
using BennyBooks.Models;
using Microsoft.AspNetCore.Mvc;
using log4net;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using BennyBooks.Models.ViewModels;

namespace BennyBooksWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class ProductController : Controller
{
    private readonly IUnitOfWork _unityOfWork; // ApplicationDbContext is now hosted in Irepository and reference in Program.cs
    private readonly IWebHostEnvironment _hostEnvironment; // use for files

    public ProductController(IUnitOfWork unityOfWork, IWebHostEnvironment hostEnvironment) // Constructor being passed db from Program.cs
    {
        _unityOfWork = unityOfWork;
        _hostEnvironment = hostEnvironment;
    }

    public IActionResult Index() // to Add new view, right click this function and Add New View and Select "Razor View"
    {
        //IEnumerable<Product> objCategoryList = _unityOfWork.Product.GetAll(); // Grabs all columns in the database, no sql required, look into LINQ            
        return View();
    }

    
    
    // UPSERT replaces Create and Edit
    public IActionResult Upsert(Guid? id)
    // Used by product.js, Upsert.cshtml same for post
    {// Unit of work allos us to access all of our controllers
        ProductVM productVM = new() // View now becomes tightly bounded by being managed in the ViewModel
        {
            Product = new(),
            CategoryList = _unityOfWork.Category.GetAll().Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }),
            CoverTypeList = _unityOfWork.CoverType.GetAll().Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }),
        };

        if (id == null && id != Guid.Empty)
        {
            return View(productVM);
        }
        else
        {
            // Will display edit page with all the data for a product
            productVM.Product = _unityOfWork.Product.GetFirstOrDefault(u => u.Id == id);
            return View(productVM);
            // Update product
        }

        
    }


    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Upsert(ProductVM obj, IFormFile file)
    {
        // Validation check making sure fields don't match
        //if (string.IsNullOrWhiteSpace(obj.Title))
        //{
        //    ModelState.AddModelError("Title", "The Title cannot be made of only whitespace."); // key for AddModel can be CustomerError or field
        //}


        // Checks to make sure the model is valid
        if (ModelState.IsValid )//&& !string.IsNullOrWhiteSpace(obj.Title
        {
            try
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null) // We have an image to add or update Upload
                {
                    string fileName = Path.GetFileNameWithoutExtension(file.FileName) + "_" + Guid.NewGuid().ToString(); // makes sure if a similar file name is create, we can replace it
                    string uploads = Path.Combine(wwwRootPath, @"images\products");
                    string extentsion = Path.GetExtension(file.FileName);

                    if (obj.Product.ImageUrl != null) // an image already exists, we should replace it
                    {
                        string oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath)) // remove previous image
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    // Copy image to our folder
                    using (Stream fileStreams = new FileStream(Path.Combine(uploads, fileName + extentsion), FileMode.Create))
                    {

                        file.CopyTo(fileStreams);
                    }
                    obj.Product.ImageUrl = @"\images\products\" + fileName + extentsion;
                }

                if (obj.Product.Id == Guid.Empty) // we are creating as there is no previous product
                {
                    await _unityOfWork.Product.AddAsync(obj.Product); // Id is taken from the Upsert.cshtml
                }
                else
                {
                    _unityOfWork.Product.Update(obj.Product);
                }

                TempData["success"] = "Product updated successfully";
                await _unityOfWork.SaveAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }

            return RedirectToAction(nameof(Index));
        }
        return View(obj);

    }



    #region API CALLS
    [HttpGet] // will get all of the products
    public IActionResult GetAll() //admin/product/getall
    {
        var productLlist = _unityOfWork.Product.GetAll(includeProperties:"Category,CoverType"); // case sensitive for properties
        return Json(new { data = productLlist });
    }

    // POST
    [HttpDelete]
    public IActionResult Delete(Guid? id) // no need for a delete GET
    {
        var obj = _unityOfWork.Product.GetFirstOrDefault(c => c.Id == id); // find obj to delete be id
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }

        string oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath)) // remove previous image
        {
            System.IO.File.Delete(oldImagePath);
        }

        _unityOfWork.Product.Remove(obj); // Update the database

        _unityOfWork.SaveAsync();
        return Json(new { success = true, message = "Delete Successful" });
        //TempData["success"] = "obj created successfully";
    }
    #endregion

}

BennyBooksWeb/Areas/Customer/Controllers/CartController.cs
using BennyBooks.DataAccess.Repository.IRepository;
using BennyBooks.Models;
using BennyBooks.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BennyBooksWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork; // use Dependancy injection to access the rest of our Models
        private readonly IEmailSender _emailSender;
        public int OrderTotal { get; set; }
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork, IEmailSender emailSender)
        {
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
        }


        public IActionResult Index()
        {
            if (User.Identity is ClaimsIdentity claimsIdentity) // casting using pattern matching https://docs.microsoft.com/en-Us/dotnet/csharp/fundamentals/tutorials/safely-cast-using-pattern-matching-is-and-as-operators
            {
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier); // claim should not be null as we are authorizing above. Should get userId

                ShoppingCartVM = new ShoppingCartVM()
                {
                    CartList = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value,
                    includeProperties: "Product")
                };

                foreach (ShoppingCart cart in ShoppingCartVM.CartList)
                {
                    cart.Price = GetPriceBasedOnQuantity(cart.Count, cart.Product.Price, cart.Product.Price50, cart.Product.Price100);
                    ShoppingCartVM.CartTotal += cart.Price * cart.Count;
                }
            }
            

            return View(ShoppingCartVM);
        }

        public IActionResult Summary()
        {
            return View();
        }

        public async Task<IActionResult> Increase(Guid cartId)
        {
            ShoppingCart cart = await _unitOfWork.ShoppingCart.GetFirstOrDefaultAsync(x => x.Id == cartId);
            await _unitOfWork.ShoppingCart.IncrementCountAsync(cart, 1);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Decrease(Guid cartId)
        {
            ShoppingCart cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(x => x.Id == cartId);

            if (cart.Count <= 1) // delete product from cart
                _unitOfWork.ShoppingCart.Remove(cart);
            else
                await _unitOfWork.ShoppingCart.DecrementCountAsync(cart, 1);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index)); // After editing the database, take us back to our main cart page
        }
        public async Task<IActionResult> Remove(Guid cartId) // remove specific item
        {
            ShoppingCart cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(x => x.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cart);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

        public double GetPriceBasedOnQuantity(double quantity, double price, double price50, double price100)
        {
            if (quantity <= 50)
                return price;
            else
            {
                if (quantity <= 100)
                    return price50;
            }
            return price100;
        }
    }
}

BennyBooksWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BennyBooksWeb</title>
    <link rel="stylesheet" href="~/css/bootSwatchSolarTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BennyBooksWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <!--Navigation from Bootwatch Solar Theme-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @*asp-area determinds which area we will be using for our controllers and views*@
                
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                  <div class="dropdown-menu">
                      <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                      <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                      <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                      <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                      
                    <div class="dropdown-divider"></div>
                  </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" role="button" asp-area="Customer" asp-controller="Portfolio" asp-action="Index">Portfolio</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                      <i class="bi bi-cart3"></i>
                  </a>
              </li>
              </ul>
              
              <partial name="_LoginPartial" />
              @*<form class="d-flex">
                <input class="form-control me-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>*@
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @*handles notifications which uses toastr*@
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - BennyBooksWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script> @*For notifications sweetalert2*@
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/q9zpidywvakg9jqnt1pjasow97mak9f03c9dkb48sdydt4xr/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BennyBooksWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null) // Notification using toaster, this is where our notifications are
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@*Displays success and error messages*@
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}